### ISSUE TITLE
thank you for your contribution

### ISSUE THREAD

**Issue by angeluau** [ucfnlp/summarization-sing-pair-mix#1]
when your code will be published?

**Comment by loganlebanoff** [comment]
I expect the code to be published by the end of July.

**Comment by angeluau** [comment]
thank you ,waitong for your model code

**Comment by loganlebanoff** [comment]
Thanks for your interest. The model code has been added. Feel free to ask if you have any questions or problems!

**Comment by angeluau** [comment]
how to get the url_lists,and how to config the BERT uncased_L-12_H-768_A-12/bert_config.json

**Comment by loganlebanoff** [comment]
Thanks for the notice. I have just added a new commit that includes placeholders for each of the models and data. url_lists comes from the FINISHED_FILES zip file from here (https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail). The pretrained BERT files (https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip) should go in the pretrained_bert_model/ directory. The bert_config.json file coming from pretrained BERT should remain unchanged.
