### ISSUE TITLE
didn't find the folder 'url_lists'

### ISSUE THREAD

**Issue by DaveKim3872** [ucfnlp/summarization-sing-pair-mix#4]
As you said in the markdown file:

> url_lists/ (this folder is inside the FINISHED_FILES zip file in JafferWilson's link) inside the ./data/cnn_dm_unprocessed/ directory.

However after downloading and unzip the file, I didn't find such a folder inside. So where can I get this part of data. Thanks a lot.

**Comment by loganlebanoff** [comment]
Thanks for finding this issue. The url_lists folder actually comes from Abigail See's repo (https://github.com/abisee/cnn-dailymail/tree/master/url_lists). I fixed the problem in the newest commit. The url_lists folder is now included in the correct directory so you don't have to find it.
