### ISSUE TITLE
custom data

### ISSUE THREAD

**Issue by antonysama** [ucfnlp/summarization-sing-pair-mix#7]
I enjoyed reading the paper and noticed the three separate data sets. How would one start running models on data outside of these data sets? Or, even how would one include a few news articles or some other text together with the data sets you used?

**Comment by loganlebanoff** [comment]
Thanks for your interest! I just added a section to the Readme about how to handle custom datasets (https://github.com/ucfnlp/summarization-sing-pair-mix#i-have-my-own-data-and-i-want-to-generate-the-singletonspairs-of-sentences-from-my-data). 

If you want to add your own articles to existing datasets, then you can simply add the articles and summaries to "articles.tsv" and "summaries.tsv," respectively, that were generated in step 2 of "Generating the data."

**Comment by antonysama** [comment]
@loganlebanoff ,

Thank you, I will try these.
