### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by shellycsy** [ucfnlp/summarization-sing-pair-mix#8]
hello，thanks for sharing !
    when i run "python preprocess_for_bert_fine_tuning.py --dataset_name=cnn_dm“，i met the problem :
Traceback (most recent call last):
  File "preprocess_for_bert_fine_tuning.py", line 178, in <module>
    app.run(main)
  File "/home/csy/anaconda/lib/python3.5/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/csy/anaconda/lib/python3.5/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "preprocess_for_bert_fine_tuning.py", line 116, in main
    rel_sent_indices, _, _ = ssi_functions.get_rel_sent_indices(doc_indices, article_sent_tokens)
  File "/home/csy/summarization-sing-pair-mix/ssi_functions.py", line 272, in get_rel_sent_indices
    sent_doc = [sent[0] for sent in doc_indices_sent_tokens]
  File "/home/csy/summarization-sing-pair-mix/ssi_functions.py", line 272, in <listcomp>
    sent_doc = [sent[0] for sent in doc_indices_sent_tokens]
IndexError: list index out of range
     I also saw this mistake in the closed problem, but he didn't give a solution. Do you know why this mistake happened? thanks!

**Comment by shellycsy** [comment]
Can you specify the environment you used？ I mentioned this earlier because of a blank line in the document, but then I ran into some problems, which I guess were environmental.

**Comment by loganlebanoff** [comment]
Did you solve the error? Can you expand on what the solution was, if you did?

I use Python 3.6, Ubuntu 16.04, Tensorflow 1.11. Let me know if you want to know more!

**Comment by shellycsy** [comment]
I modified line 218-221 of the create_cnndm_dataset.py  .
‘      article_line = '\t'.join(article_sents) + '\n'
      abstract_line = '\t'.join(abstract_sents) + '\n'
      f_art.write(article_line.encode())
      f_abs.write(abstract_line.encode())’
changed to：
      if article_sents :
          article_line = '\t'.join(article_sents) + '\n'
          f_art.write(article_line.encode())
      if abstract_sents :
          abstract_line = '\t'.join(abstract_sents) + '\n'
          f_abs.write(abstract_line.encode())

There was a problem in the middle, but I forgot to record it, because I solved the problem after upgrading tensorflow to 1.9.0. If I encounter other problems, I will contact you again, thank you.

**Comment by loganlebanoff** [comment]
Ok thanks for the info.
